In [1]:
# Importing Libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split
import quandl
import pandas as pd
import re
import numpy as np
import tqdm
import matplotlib.pyplot as plt
import geopandas as gpd
import seaborn as sns

# Importing Data
JT_JB = pd.read_csv(r"C:\Users\richa\Downloads\JT_JB.csv")

## Naive Bayes: Team Metrics

In [4]:
# New Dataframe
last_rows = JT_JB.groupby(['Year','Game', 'Q']).last().reset_index()
last_rows = last_rows[last_rows['Q']=='Q3']

df_nb = last_rows[['Result', 'Year', 'BOS_FG', 'OPP_FG']].copy()
df_nb['Result'] = np.where(df_nb['Result'] == 'BOS', 1, 0)

In [5]:
# Split
df_nb_train = df_nb[df_nb['Year'] != 2023]
df_nb_test =df_nb[df_nb['Year'] == 2023]


# Drop
X_train = df_nb_train.drop(['Result', 'Year'], axis=1)
y_train = df_nb_train['Result']
X_test = df_nb_test.drop(['Result', 'Year'], axis=1)
y_test = df_nb_test['Result']

In [6]:
# model
model = GaussianNB()

# training
model.fit(X_train, y_train)

GaussianNB()

### Testing: Team Metrics

In [7]:
# test
y_pred = model.predict(X_test)

# eval
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

auc_score = roc_auc_score(y_test, y_pred)
print("ROC AUC Score:", auc_score)

Accuracy: 0.759493670886076
Confusion Matrix:
 [[18  6]
 [13 42]]
ROC AUC Score: 0.7568181818181818


## Naive Bayes: Player Metrics

In [3]:
# Dataframe
last_rows_JT_JB = JT_JB.groupby(['Year','Game', 'Q']).last().reset_index()
last_rows_JT_JB = last_rows_JT_JB[last_rows_JT_JB['Q']=='Q3']

jtjb_df_nb = last_rows_JT_JB[['Result', 'Year', 'JT_FG', 'JB_FG']].copy()
jtjb_df_nb['Result'] = np.where(jtjb_df_nb['Result'] == 'BOS', 1, 0)

Accuracy: 0.43037974683544306
Confusion Matrix:
 [[22  2]
 [43 12]]
ROC AUC Score: 0.5674242424242424


In [8]:
# Split
jtjb_nb_train = jtjb_df_nb[df_nb['Year'] != 2023]
jtjb_nb_test = jtjb_df_nb[df_nb['Year'] == 2023]


# Drop
X_train_jtjb = jtjb_nb_train.drop(['Result', 'Year'], axis=1)
y_train_jtjb = jtjb_nb_train['Result']
X_test_jtjb = jtjb_nb_test.drop(['Result', 'Year'], axis=1)
y_test_jtjb = jtjb_nb_test['Result']

In [9]:
# Model
model = GaussianNB()

# Training
model.fit(X_train_jtjb, y_train_jtjb)


GaussianNB()

### Testing: Player Metrics

In [10]:
# test
y_pred = model.predict(X_test_jtjb)

# eval
accuracy = accuracy_score(y_test_jtjb, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test_jtjb, y_pred)
print("Confusion Matrix:\n", conf_matrix)

auc_score = roc_auc_score(y_test_jtjb, y_pred)
print("ROC AUC Score:", auc_score)

Accuracy: 0.43037974683544306
Confusion Matrix:
 [[22  2]
 [43 12]]
ROC AUC Score: 0.5674242424242424
